# Generated by Django 4.0.5 on 2022-06-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
